default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index"}

default_view:
    path: /view
    defaults: { _controller: "AppBundle:Default:view" }

default_search:
    path: /search
    defaults: { _controller: "AppBundle:Default:search" }